name: jonathanlang
favicon: null
layout_spectrum: 0.26279
typography_spectrum: 0.3779
title: Jonathan Lang - Digital Media Guy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8f7157'
    - '#f3fbfe'
    - '#00acf3'
    - '#6c0ff6'
  brandStrength: 0.12791985529474914
  lightness: 0.49128770432434976
  saturation: 0.9439833394717425
  rhythmicContrast: 0.9093228029087186
purpose: []
