name: jonathanlang
favicon: null
layout_spectrum: 0.4177376206498593
typography_spectrum: 0.7056715283542871
title: Jonathan Lang - Digital Media Guy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.12791985529474914
  lightness: 0.49128770432434976
  saturation: 0.9439833394717425
  rhythmicContrast: 0.9093228029087186
purpose: []
